title: Cristiane Silva # your name (or website title) here
logo: "/images/minha_foto.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with background in financial forecasting.
  
  <br><br>
  <a href="https://www.linkedin.com/in/ssilvacris/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://medium.com/@cristianesilva_10348">View My Blog Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
