title: <p> Cristiane Silva </p>
logo: "/images/minha_foto.jpeg?raw=true" 
description: > 
  Data Scientist with background in financial forecasting.
  
  <a href="https://www.linkedin.com/in/ssilvacris/">LinkedIn</a> |
  <a href="https://medium.com/@cristianesilva_10348">Medium</a>|
  <a href="https://github.com/ssilvacris">Github</a>
  
theme: jekyll-theme-minimal
google_analytics: G-1SFYTXV90S # your Google Analytics tracking ID here
